---
platform: linux
image_resource:
  type: docker-image
  source: {repository: bosh/integration}

inputs:
  - name: environment
  - name: bosh-cpi-src

run:
  path: bosh-cpi-src/ci/tasks/cleanup-images-in-gallery.sh

params:
  AZURE_ENVIRONMENT:                                 ""
  AZURE_SUBSCRIPTION_ID:                             ""
  AZURE_CLIENT_ID:                                   ""
  AZURE_CLIENT_SECRET:                               ""
  AZURE_TENANT_ID:                                   ""
